#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
# autospec version: v27
# autospec commit: 65cf152
#
Name     : yosys
Version  : 0.54
Release  : 1
URL      : https://github.com/YosysHQ/yosys/releases/download/v0.54/yosys.tar.gz
Source0  : https://github.com/YosysHQ/yosys/releases/download/v0.54/yosys.tar.gz
Summary  : @PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : BSD-3-Clause MIT bzip2-1.0.5
Requires: yosys-license = %{version}-%{release}
Requires: yosys-python = %{version}-%{release}
Requires: yosys-python3 = %{version}-%{release}
BuildRequires : bison
BuildRequires : boost-dev
BuildRequires : boost-extras
BuildRequires : buildreq-distutils3
BuildRequires : flex
BuildRequires : libffi-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
**************************************************************************
*                                                                        *
*                    The SubCircuit C++11 library                        *
*                                                                        *
* An implementation of a modified Ullmann Subgraph Isomorphism Algorithm *
* for coarse grain logic networks.                  by Claire Xenia Wolf *
*                                                                        *
**************************************************************************

%package dev
Summary: dev components for the yosys package.
Group: Development
Provides: yosys-devel = %{version}-%{release}
Requires: yosys = %{version}-%{release}

%description dev
dev components for the yosys package.


%package license
Summary: license components for the yosys package.
Group: Default

%description license
license components for the yosys package.


%package python
Summary: python components for the yosys package.
Group: Default
Requires: yosys-python3 = %{version}-%{release}

%description python
python components for the yosys package.


%package python3
Summary: python3 components for the yosys package.
Group: Default
Requires: python3-core
Provides: pypi(yosys)
Requires: pypi(setuptools)
Requires: pypi(wheel)

%description python3
python3 components for the yosys package.


%prep
%setup -q -c -n yosys.tar
cd %{_builddir}/yosys.tar

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749480217
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yosys
cp %{_builddir}/yosys.tar/abc/src/bdd/cudd/license %{buildroot}/usr/share/package-licenses/yosys/af63e05f5b9b61148165ffd906d5b5340c53dfa4 || :
cp %{_builddir}/yosys.tar/abc/src/misc/bzlib/LICENSE %{buildroot}/usr/share/package-licenses/yosys/d964dbe91cbf7511e4f1857db9e99fdaf6658055 || :
cp %{_builddir}/yosys.tar/abc/src/sat/bsat/license %{buildroot}/usr/share/package-licenses/yosys/bf11c823b285da2982ce37c81f986e3919717e22 || :
cp %{_builddir}/yosys.tar/abc/src/sat/bsat2/LICENSE %{buildroot}/usr/share/package-licenses/yosys/147967ece0e908b71e49bdc89726009323fa13eb || :
cp %{_builddir}/yosys.tar/abc/src/sat/cadical/LICENSE %{buildroot}/usr/share/package-licenses/yosys/e132aa0888797f50bdd288fd7bdbbd6fe1668d97 || :
cp %{_builddir}/yosys.tar/abc/src/sat/glucose/license %{buildroot}/usr/share/package-licenses/yosys/4e816e2dac959a00d5417c5596962de7ea030578 || :
cp %{_builddir}/yosys.tar/abc/src/sat/glucose2/license %{buildroot}/usr/share/package-licenses/yosys/4e816e2dac959a00d5417c5596962de7ea030578 || :
cp %{_builddir}/yosys.tar/abc/src/sat/kissat/LICENSE %{buildroot}/usr/share/package-licenses/yosys/8e8ba7c0818382c4570e3e2d22722d571fc4f3f6 || :
cp %{_builddir}/yosys.tar/abc/src/sat/xsat/license %{buildroot}/usr/share/package-licenses/yosys/378229f8ff41cde7e05ee1b9c2397b46b28a0aad || :
cp %{_builddir}/yosys.tar/libs/cxxopts/LICENSE %{buildroot}/usr/share/package-licenses/yosys/a80d953c86d2e556e39010923349a73cc3c5c0be || :
cp %{_builddir}/yosys.tar/libs/minisat/LICENSE %{buildroot}/usr/share/package-licenses/yosys/147967ece0e908b71e49bdc89726009323fa13eb || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.13/site-packages/pyosys/share/include/backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi.h
/usr/lib/python3.13/site-packages/pyosys/share/include/backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi_vcd.h
/usr/lib/python3.13/site-packages/pyosys/share/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
/usr/lib/python3.13/site-packages/pyosys/share/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl_replay.h
/usr/lib/python3.13/site-packages/pyosys/share/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl_time.h
/usr/lib/python3.13/site-packages/pyosys/share/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl_vcd.h
/usr/lib/python3.13/site-packages/pyosys/share/include/backends/rtlil/rtlil_backend.h
/usr/lib/python3.13/site-packages/pyosys/share/include/frontends/ast/ast.h
/usr/lib/python3.13/site-packages/pyosys/share/include/frontends/ast/ast_binding.h
/usr/lib/python3.13/site-packages/pyosys/share/include/frontends/blif/blifparse.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/binding.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/bitpattern.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/cellaigs.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/celledges.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/celltypes.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/consteval.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/cost.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/drivertools.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/ff.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/ffinit.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/ffmerge.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/fmt.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/fstdata.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/gzip.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/hashlib.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/io.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/json.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/log.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/macc.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/mem.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/modtools.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/qcsat.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/register.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/rtlil.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/satgen.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/scopeinfo.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/sexpr.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/sigtools.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/timinginfo.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/utils.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/yosys.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/yosys_common.h
/usr/lib/python3.13/site-packages/pyosys/share/include/kernel/yw.h
/usr/lib/python3.13/site-packages/pyosys/share/include/libs/ezsat/ezminisat.h
/usr/lib/python3.13/site-packages/pyosys/share/include/libs/ezsat/ezsat.h
/usr/lib/python3.13/site-packages/pyosys/share/include/libs/fst/fstapi.h
/usr/lib/python3.13/site-packages/pyosys/share/include/libs/sha1/sha1.h
/usr/lib/python3.13/site-packages/pyosys/share/include/passes/fsm/fsmdata.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yosys/147967ece0e908b71e49bdc89726009323fa13eb
/usr/share/package-licenses/yosys/378229f8ff41cde7e05ee1b9c2397b46b28a0aad
/usr/share/package-licenses/yosys/4e816e2dac959a00d5417c5596962de7ea030578
/usr/share/package-licenses/yosys/8e8ba7c0818382c4570e3e2d22722d571fc4f3f6
/usr/share/package-licenses/yosys/a80d953c86d2e556e39010923349a73cc3c5c0be
/usr/share/package-licenses/yosys/af63e05f5b9b61148165ffd906d5b5340c53dfa4
/usr/share/package-licenses/yosys/bf11c823b285da2982ce37c81f986e3919717e22
/usr/share/package-licenses/yosys/d964dbe91cbf7511e4f1857db9e99fdaf6658055
/usr/share/package-licenses/yosys/e132aa0888797f50bdd288fd7bdbbd6fe1668d97

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
