#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v27
# autospec commit: 65cf152
#
Name     : yosys
Version  : 0.54
Release  : 2
URL      : https://github.com/YosysHQ/yosys/releases/download/v0.54/yosys.tar.gz
Source0  : https://github.com/YosysHQ/yosys/releases/download/v0.54/yosys.tar.gz
Summary  : @PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : BSD-3-Clause MIT bzip2-1.0.5
Requires: yosys-bin = %{version}-%{release}
Requires: yosys-data = %{version}-%{release}
Requires: yosys-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : boost-dev
BuildRequires : boost-extras
BuildRequires : flex
BuildRequires : libffi-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : readline-dev
BuildRequires : tcl
BuildRequires : tcl-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: nolocal.patch

%description
**************************************************************************
*                                                                        *
*                    The SubCircuit C++11 library                        *
*                                                                        *
* An implementation of a modified Ullmann Subgraph Isomorphism Algorithm *
* for coarse grain logic networks.                  by Claire Xenia Wolf *
*                                                                        *
**************************************************************************

%package bin
Summary: bin components for the yosys package.
Group: Binaries
Requires: yosys-data = %{version}-%{release}
Requires: yosys-license = %{version}-%{release}

%description bin
bin components for the yosys package.


%package data
Summary: data components for the yosys package.
Group: Data

%description data
data components for the yosys package.


%package dev
Summary: dev components for the yosys package.
Group: Development
Requires: yosys-bin = %{version}-%{release}
Requires: yosys-data = %{version}-%{release}
Provides: yosys-devel = %{version}-%{release}
Requires: yosys = %{version}-%{release}

%description dev
dev components for the yosys package.


%package license
Summary: license components for the yosys package.
Group: Default

%description license
license components for the yosys package.


%prep
%setup -q -c -n yosys.tar
cd %{_builddir}/yosys.tar
%patch -P 1 -p1

%build
## build_prepend content
make config-gcc
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749484472
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1749484472
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yosys
cp %{_builddir}/yosys.tar/abc/src/bdd/cudd/license %{buildroot}/usr/share/package-licenses/yosys/af63e05f5b9b61148165ffd906d5b5340c53dfa4 || :
cp %{_builddir}/yosys.tar/abc/src/misc/bzlib/LICENSE %{buildroot}/usr/share/package-licenses/yosys/d964dbe91cbf7511e4f1857db9e99fdaf6658055 || :
cp %{_builddir}/yosys.tar/abc/src/sat/bsat/license %{buildroot}/usr/share/package-licenses/yosys/bf11c823b285da2982ce37c81f986e3919717e22 || :
cp %{_builddir}/yosys.tar/abc/src/sat/bsat2/LICENSE %{buildroot}/usr/share/package-licenses/yosys/147967ece0e908b71e49bdc89726009323fa13eb || :
cp %{_builddir}/yosys.tar/abc/src/sat/cadical/LICENSE %{buildroot}/usr/share/package-licenses/yosys/e132aa0888797f50bdd288fd7bdbbd6fe1668d97 || :
cp %{_builddir}/yosys.tar/abc/src/sat/glucose/license %{buildroot}/usr/share/package-licenses/yosys/4e816e2dac959a00d5417c5596962de7ea030578 || :
cp %{_builddir}/yosys.tar/abc/src/sat/glucose2/license %{buildroot}/usr/share/package-licenses/yosys/4e816e2dac959a00d5417c5596962de7ea030578 || :
cp %{_builddir}/yosys.tar/abc/src/sat/kissat/LICENSE %{buildroot}/usr/share/package-licenses/yosys/8e8ba7c0818382c4570e3e2d22722d571fc4f3f6 || :
cp %{_builddir}/yosys.tar/abc/src/sat/xsat/license %{buildroot}/usr/share/package-licenses/yosys/378229f8ff41cde7e05ee1b9c2397b46b28a0aad || :
cp %{_builddir}/yosys.tar/libs/cxxopts/LICENSE %{buildroot}/usr/share/package-licenses/yosys/a80d953c86d2e556e39010923349a73cc3c5c0be || :
cp %{_builddir}/yosys.tar/libs/minisat/LICENSE %{buildroot}/usr/share/package-licenses/yosys/147967ece0e908b71e49bdc89726009323fa13eb || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yosys
/usr/bin/yosys-abc
/usr/bin/yosys-config
/usr/bin/yosys-filterlib
/usr/bin/yosys-smtbmc
/usr/bin/yosys-witness

%files data
%defattr(-,root,root,-)
/usr/share/yosys/abc9_map.v
/usr/share/yosys/abc9_model.v
/usr/share/yosys/abc9_unmap.v
/usr/share/yosys/achronix/speedster22i/cells_map.v
/usr/share/yosys/achronix/speedster22i/cells_sim.v
/usr/share/yosys/adff2dff.v
/usr/share/yosys/anlogic/arith_map.v
/usr/share/yosys/anlogic/brams.txt
/usr/share/yosys/anlogic/brams_map.v
/usr/share/yosys/anlogic/cells_map.v
/usr/share/yosys/anlogic/cells_sim.v
/usr/share/yosys/anlogic/eagle_bb.v
/usr/share/yosys/anlogic/lutrams.txt
/usr/share/yosys/anlogic/lutrams_map.v
/usr/share/yosys/cells.lib
/usr/share/yosys/choices/han-carlson.v
/usr/share/yosys/choices/kogge-stone.v
/usr/share/yosys/choices/sklansky.v
/usr/share/yosys/cmp2lcu.v
/usr/share/yosys/cmp2lut.v
/usr/share/yosys/cmp2softlogic.v
/usr/share/yosys/coolrunner2/cells_counter_map.v
/usr/share/yosys/coolrunner2/cells_latch.v
/usr/share/yosys/coolrunner2/cells_sim.v
/usr/share/yosys/coolrunner2/tff_extract.v
/usr/share/yosys/coolrunner2/xc2_dff.lib
/usr/share/yosys/dff2ff.v
/usr/share/yosys/ecp5/arith_map.v
/usr/share/yosys/ecp5/brams.txt
/usr/share/yosys/ecp5/brams_map.v
/usr/share/yosys/ecp5/cells_bb.v
/usr/share/yosys/ecp5/cells_ff.vh
/usr/share/yosys/ecp5/cells_io.vh
/usr/share/yosys/ecp5/cells_map.v
/usr/share/yosys/ecp5/cells_sim.v
/usr/share/yosys/ecp5/dsp_map.v
/usr/share/yosys/ecp5/latches_map.v
/usr/share/yosys/ecp5/lutrams.txt
/usr/share/yosys/ecp5/lutrams_map.v
/usr/share/yosys/efinix/arith_map.v
/usr/share/yosys/efinix/brams.txt
/usr/share/yosys/efinix/brams_map.v
/usr/share/yosys/efinix/cells_map.v
/usr/share/yosys/efinix/cells_sim.v
/usr/share/yosys/efinix/gbuf_map.v
/usr/share/yosys/fabulous/arith_map.v
/usr/share/yosys/fabulous/cells_map.v
/usr/share/yosys/fabulous/ff_map.v
/usr/share/yosys/fabulous/io_map.v
/usr/share/yosys/fabulous/latches_map.v
/usr/share/yosys/fabulous/prims.v
/usr/share/yosys/fabulous/ram_regfile.txt
/usr/share/yosys/fabulous/regfile_map.v
/usr/share/yosys/gate2lut.v
/usr/share/yosys/gatemate/arith_map.v
/usr/share/yosys/gatemate/brams.txt
/usr/share/yosys/gatemate/brams_init_20.vh
/usr/share/yosys/gatemate/brams_init_40.vh
/usr/share/yosys/gatemate/brams_map.v
/usr/share/yosys/gatemate/cells_bb.v
/usr/share/yosys/gatemate/cells_sim.v
/usr/share/yosys/gatemate/inv_map.v
/usr/share/yosys/gatemate/lut_map.v
/usr/share/yosys/gatemate/lut_tree_cells.genlib
/usr/share/yosys/gatemate/lut_tree_map.v
/usr/share/yosys/gatemate/mul_map.v
/usr/share/yosys/gatemate/mux_map.v
/usr/share/yosys/gatemate/reg_map.v
/usr/share/yosys/gowin/arith_map.v
/usr/share/yosys/gowin/brams.txt
/usr/share/yosys/gowin/brams_map.v
/usr/share/yosys/gowin/cells_map.v
/usr/share/yosys/gowin/cells_sim.v
/usr/share/yosys/gowin/cells_xtra_gw1n.v
/usr/share/yosys/gowin/cells_xtra_gw2a.v
/usr/share/yosys/gowin/cells_xtra_gw5a.v
/usr/share/yosys/gowin/lutrams.txt
/usr/share/yosys/gowin/lutrams_map.v
/usr/share/yosys/greenpak4/cells_blackbox.v
/usr/share/yosys/greenpak4/cells_latch.v
/usr/share/yosys/greenpak4/cells_map.v
/usr/share/yosys/greenpak4/cells_sim.v
/usr/share/yosys/greenpak4/cells_sim_ams.v
/usr/share/yosys/greenpak4/cells_sim_digital.v
/usr/share/yosys/greenpak4/cells_sim_wip.v
/usr/share/yosys/greenpak4/gp_dff.lib
/usr/share/yosys/ice40/abc9_model.v
/usr/share/yosys/ice40/arith_map.v
/usr/share/yosys/ice40/brams.txt
/usr/share/yosys/ice40/brams_map.v
/usr/share/yosys/ice40/cells_map.v
/usr/share/yosys/ice40/cells_sim.v
/usr/share/yosys/ice40/dsp_map.v
/usr/share/yosys/ice40/ff_map.v
/usr/share/yosys/ice40/latches_map.v
/usr/share/yosys/ice40/spram.txt
/usr/share/yosys/ice40/spram_map.v
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi.cc
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi_vcd.cc
/usr/share/yosys/include/kernel/constids.inc
/usr/share/yosys/include/libs/json11/json11.hpp
/usr/share/yosys/intel/common/altpll_bb.v
/usr/share/yosys/intel/common/brams_m9k.txt
/usr/share/yosys/intel/common/brams_map_m9k.v
/usr/share/yosys/intel/common/ff_map.v
/usr/share/yosys/intel/common/m9k_bb.v
/usr/share/yosys/intel/cyclone10lp/cells_map.v
/usr/share/yosys/intel/cyclone10lp/cells_sim.v
/usr/share/yosys/intel/cycloneiv/cells_map.v
/usr/share/yosys/intel/cycloneiv/cells_sim.v
/usr/share/yosys/intel/cycloneive/cells_map.v
/usr/share/yosys/intel/cycloneive/cells_sim.v
/usr/share/yosys/intel/max10/cells_map.v
/usr/share/yosys/intel/max10/cells_sim.v
/usr/share/yosys/intel_alm/common/abc9_map.v
/usr/share/yosys/intel_alm/common/abc9_model.v
/usr/share/yosys/intel_alm/common/abc9_unmap.v
/usr/share/yosys/intel_alm/common/alm_map.v
/usr/share/yosys/intel_alm/common/alm_sim.v
/usr/share/yosys/intel_alm/common/arith_alm_map.v
/usr/share/yosys/intel_alm/common/bram_m10k.txt
/usr/share/yosys/intel_alm/common/bram_m10k_map.v
/usr/share/yosys/intel_alm/common/dff_map.v
/usr/share/yosys/intel_alm/common/dff_sim.v
/usr/share/yosys/intel_alm/common/dsp_map.v
/usr/share/yosys/intel_alm/common/dsp_sim.v
/usr/share/yosys/intel_alm/common/lutram_mlab.txt
/usr/share/yosys/intel_alm/common/megafunction_bb.v
/usr/share/yosys/intel_alm/common/mem_sim.v
/usr/share/yosys/intel_alm/common/misc_sim.v
/usr/share/yosys/intel_alm/cyclonev/cells_sim.v
/usr/share/yosys/lattice/arith_map_ccu2c.v
/usr/share/yosys/lattice/arith_map_ccu2d.v
/usr/share/yosys/lattice/brams_16kd.txt
/usr/share/yosys/lattice/brams_8kc.txt
/usr/share/yosys/lattice/brams_map_16kd.v
/usr/share/yosys/lattice/brams_map_8kc.v
/usr/share/yosys/lattice/ccu2c_sim.vh
/usr/share/yosys/lattice/ccu2d_sim.vh
/usr/share/yosys/lattice/cells_bb_ecp5.v
/usr/share/yosys/lattice/cells_bb_xo2.v
/usr/share/yosys/lattice/cells_bb_xo3.v
/usr/share/yosys/lattice/cells_bb_xo3d.v
/usr/share/yosys/lattice/cells_ff.vh
/usr/share/yosys/lattice/cells_io.vh
/usr/share/yosys/lattice/cells_map.v
/usr/share/yosys/lattice/cells_sim_ecp5.v
/usr/share/yosys/lattice/cells_sim_xo2.v
/usr/share/yosys/lattice/cells_sim_xo3.v
/usr/share/yosys/lattice/cells_sim_xo3d.v
/usr/share/yosys/lattice/common_sim.vh
/usr/share/yosys/lattice/dsp_map_18x18.v
/usr/share/yosys/lattice/latches_map.v
/usr/share/yosys/lattice/lutrams.txt
/usr/share/yosys/lattice/lutrams_map.v
/usr/share/yosys/microchip/LSRAM.txt
/usr/share/yosys/microchip/LSRAM_map.v
/usr/share/yosys/microchip/arith_map.v
/usr/share/yosys/microchip/brams_defs.vh
/usr/share/yosys/microchip/cells_map.v
/usr/share/yosys/microchip/cells_sim.v
/usr/share/yosys/microchip/polarfire_dsp_map.v
/usr/share/yosys/microchip/uSRAM.txt
/usr/share/yosys/microchip/uSRAM_map.v
/usr/share/yosys/mul2dsp.v
/usr/share/yosys/nanoxplore/arith_map.v
/usr/share/yosys/nanoxplore/brams.txt
/usr/share/yosys/nanoxplore/brams_init.vh
/usr/share/yosys/nanoxplore/brams_map.v
/usr/share/yosys/nanoxplore/cells_bb.v
/usr/share/yosys/nanoxplore/cells_bb_l.v
/usr/share/yosys/nanoxplore/cells_bb_m.v
/usr/share/yosys/nanoxplore/cells_bb_u.v
/usr/share/yosys/nanoxplore/cells_map.v
/usr/share/yosys/nanoxplore/cells_sim.v
/usr/share/yosys/nanoxplore/cells_sim_l.v
/usr/share/yosys/nanoxplore/cells_sim_m.v
/usr/share/yosys/nanoxplore/cells_sim_u.v
/usr/share/yosys/nanoxplore/cells_wrap.v
/usr/share/yosys/nanoxplore/cells_wrap_l.v
/usr/share/yosys/nanoxplore/cells_wrap_m.v
/usr/share/yosys/nanoxplore/cells_wrap_u.v
/usr/share/yosys/nanoxplore/io_map.v
/usr/share/yosys/nanoxplore/latches_map.v
/usr/share/yosys/nanoxplore/rf_init.vh
/usr/share/yosys/nanoxplore/rf_rams_l.txt
/usr/share/yosys/nanoxplore/rf_rams_m.txt
/usr/share/yosys/nanoxplore/rf_rams_map_l.v
/usr/share/yosys/nanoxplore/rf_rams_map_m.v
/usr/share/yosys/nanoxplore/rf_rams_map_u.v
/usr/share/yosys/nanoxplore/rf_rams_u.txt
/usr/share/yosys/nexus/arith_map.v
/usr/share/yosys/nexus/brams.txt
/usr/share/yosys/nexus/brams_map.v
/usr/share/yosys/nexus/cells_map.v
/usr/share/yosys/nexus/cells_sim.v
/usr/share/yosys/nexus/cells_xtra.v
/usr/share/yosys/nexus/dsp_map.v
/usr/share/yosys/nexus/latches_map.v
/usr/share/yosys/nexus/lrams.txt
/usr/share/yosys/nexus/lrams_map.v
/usr/share/yosys/nexus/lutrams.txt
/usr/share/yosys/nexus/lutrams_map.v
/usr/share/yosys/nexus/parse_init.vh
/usr/share/yosys/pmux2mux.v
/usr/share/yosys/python3/smtio.py
/usr/share/yosys/python3/ywio.py
/usr/share/yosys/quicklogic/common/cells_sim.v
/usr/share/yosys/quicklogic/pp3/abc9_map.v
/usr/share/yosys/quicklogic/pp3/abc9_model.v
/usr/share/yosys/quicklogic/pp3/abc9_unmap.v
/usr/share/yosys/quicklogic/pp3/cells_map.v
/usr/share/yosys/quicklogic/pp3/cells_sim.v
/usr/share/yosys/quicklogic/pp3/ffs_map.v
/usr/share/yosys/quicklogic/pp3/latches_map.v
/usr/share/yosys/quicklogic/pp3/lut_map.v
/usr/share/yosys/quicklogic/qlf_k6n10f/TDP18K_FIFO.v
/usr/share/yosys/quicklogic/qlf_k6n10f/arith_map.v
/usr/share/yosys/quicklogic/qlf_k6n10f/bram_types_sim.v
/usr/share/yosys/quicklogic/qlf_k6n10f/brams_map.v
/usr/share/yosys/quicklogic/qlf_k6n10f/brams_sim.v
/usr/share/yosys/quicklogic/qlf_k6n10f/cells_sim.v
/usr/share/yosys/quicklogic/qlf_k6n10f/dsp_final_map.v
/usr/share/yosys/quicklogic/qlf_k6n10f/dsp_map.v
/usr/share/yosys/quicklogic/qlf_k6n10f/dsp_sim.v
/usr/share/yosys/quicklogic/qlf_k6n10f/ffs_map.v
/usr/share/yosys/quicklogic/qlf_k6n10f/libmap_brams.txt
/usr/share/yosys/quicklogic/qlf_k6n10f/libmap_brams_map.v
/usr/share/yosys/quicklogic/qlf_k6n10f/sram1024x18_mem.v
/usr/share/yosys/quicklogic/qlf_k6n10f/ufifo_ctl.v
/usr/share/yosys/sf2/arith_map.v
/usr/share/yosys/sf2/cells_map.v
/usr/share/yosys/sf2/cells_sim.v
/usr/share/yosys/simcells.v
/usr/share/yosys/simlib.v
/usr/share/yosys/smtmap.v
/usr/share/yosys/techmap.v
/usr/share/yosys/xilinx/abc9_model.v
/usr/share/yosys/xilinx/arith_map.v
/usr/share/yosys/xilinx/brams_defs.vh
/usr/share/yosys/xilinx/brams_xc2v.txt
/usr/share/yosys/xilinx/brams_xc2v_map.v
/usr/share/yosys/xilinx/brams_xc3sda.txt
/usr/share/yosys/xilinx/brams_xc3sda_map.v
/usr/share/yosys/xilinx/brams_xc4v.txt
/usr/share/yosys/xilinx/brams_xc4v_map.v
/usr/share/yosys/xilinx/brams_xc5v_map.v
/usr/share/yosys/xilinx/brams_xc6v_map.v
/usr/share/yosys/xilinx/brams_xcu_map.v
/usr/share/yosys/xilinx/brams_xcv.txt
/usr/share/yosys/xilinx/brams_xcv_map.v
/usr/share/yosys/xilinx/cells_map.v
/usr/share/yosys/xilinx/cells_sim.v
/usr/share/yosys/xilinx/cells_xtra.v
/usr/share/yosys/xilinx/ff_map.v
/usr/share/yosys/xilinx/lut_map.v
/usr/share/yosys/xilinx/lutrams_xc5v.txt
/usr/share/yosys/xilinx/lutrams_xc5v_map.v
/usr/share/yosys/xilinx/lutrams_xcu.txt
/usr/share/yosys/xilinx/lutrams_xcv.txt
/usr/share/yosys/xilinx/lutrams_xcv_map.v
/usr/share/yosys/xilinx/mux_map.v
/usr/share/yosys/xilinx/urams.txt
/usr/share/yosys/xilinx/urams_map.v
/usr/share/yosys/xilinx/xc3s_mult_map.v
/usr/share/yosys/xilinx/xc3sda_dsp_map.v
/usr/share/yosys/xilinx/xc4v_dsp_map.v
/usr/share/yosys/xilinx/xc5v_dsp_map.v
/usr/share/yosys/xilinx/xc6s_dsp_map.v
/usr/share/yosys/xilinx/xc7_dsp_map.v
/usr/share/yosys/xilinx/xcu_dsp_map.v

%files dev
%defattr(-,root,root,-)
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi.h
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi_vcd.h
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl_replay.h
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl_time.h
/usr/share/yosys/include/backends/cxxrtl/runtime/cxxrtl/cxxrtl_vcd.h
/usr/share/yosys/include/backends/rtlil/rtlil_backend.h
/usr/share/yosys/include/frontends/ast/ast.h
/usr/share/yosys/include/frontends/ast/ast_binding.h
/usr/share/yosys/include/frontends/blif/blifparse.h
/usr/share/yosys/include/kernel/binding.h
/usr/share/yosys/include/kernel/bitpattern.h
/usr/share/yosys/include/kernel/cellaigs.h
/usr/share/yosys/include/kernel/celledges.h
/usr/share/yosys/include/kernel/celltypes.h
/usr/share/yosys/include/kernel/consteval.h
/usr/share/yosys/include/kernel/cost.h
/usr/share/yosys/include/kernel/drivertools.h
/usr/share/yosys/include/kernel/ff.h
/usr/share/yosys/include/kernel/ffinit.h
/usr/share/yosys/include/kernel/ffmerge.h
/usr/share/yosys/include/kernel/fmt.h
/usr/share/yosys/include/kernel/fstdata.h
/usr/share/yosys/include/kernel/gzip.h
/usr/share/yosys/include/kernel/hashlib.h
/usr/share/yosys/include/kernel/io.h
/usr/share/yosys/include/kernel/json.h
/usr/share/yosys/include/kernel/log.h
/usr/share/yosys/include/kernel/macc.h
/usr/share/yosys/include/kernel/mem.h
/usr/share/yosys/include/kernel/modtools.h
/usr/share/yosys/include/kernel/qcsat.h
/usr/share/yosys/include/kernel/register.h
/usr/share/yosys/include/kernel/rtlil.h
/usr/share/yosys/include/kernel/satgen.h
/usr/share/yosys/include/kernel/scopeinfo.h
/usr/share/yosys/include/kernel/sexpr.h
/usr/share/yosys/include/kernel/sigtools.h
/usr/share/yosys/include/kernel/timinginfo.h
/usr/share/yosys/include/kernel/utils.h
/usr/share/yosys/include/kernel/yosys.h
/usr/share/yosys/include/kernel/yosys_common.h
/usr/share/yosys/include/kernel/yw.h
/usr/share/yosys/include/libs/ezsat/ezminisat.h
/usr/share/yosys/include/libs/ezsat/ezsat.h
/usr/share/yosys/include/libs/fst/fstapi.h
/usr/share/yosys/include/libs/sha1/sha1.h
/usr/share/yosys/include/passes/fsm/fsmdata.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yosys/147967ece0e908b71e49bdc89726009323fa13eb
/usr/share/package-licenses/yosys/378229f8ff41cde7e05ee1b9c2397b46b28a0aad
/usr/share/package-licenses/yosys/4e816e2dac959a00d5417c5596962de7ea030578
/usr/share/package-licenses/yosys/8e8ba7c0818382c4570e3e2d22722d571fc4f3f6
/usr/share/package-licenses/yosys/a80d953c86d2e556e39010923349a73cc3c5c0be
/usr/share/package-licenses/yosys/af63e05f5b9b61148165ffd906d5b5340c53dfa4
/usr/share/package-licenses/yosys/bf11c823b285da2982ce37c81f986e3919717e22
/usr/share/package-licenses/yosys/d964dbe91cbf7511e4f1857db9e99fdaf6658055
/usr/share/package-licenses/yosys/e132aa0888797f50bdd288fd7bdbbd6fe1668d97
